#!/bin/sh
#
# This script takes a function within a library, and outputs
# N bytes of the function's instruction signature in the form "\xff*"
# in the form of a C string
#
# ARG1 = lib name
# ARG2 = evil function name
# ARG3 = hex bytes to print out

usage () {
	echo "$0 <lib name> <evil function name> <bytecount>"
}

if [ "$#" -ne 3 ]; then
	usage
	exit 1
fi
	
echo "// DO NOT MODIFY: AUTOGENERATED"
echo -n "static char const evilsig[] = \""
echo -n "$(objdump -d $1 | \
	grep -A 30 "$2>" | \
	cut -f 2 | \
	grep -v "$2" | \
	tr '\n' '\ ' | \
	sed -E 's/(\w{2})/\\x\1/g' | \
	sed -E 's/\s+//g' | \
	cut -c1-$((4*$3)))"
echo "\";"

echo -n "static char const tc[] = \""
echo -n "$(objdump -d $1 | grep -A 20 "$2>" | grep "c7 45 f4" | cut -f 2 | sed -E 's/(\w{2})/\\x\1/g' | tr '\n' '\ ' | sed -E 's/\s+//g' | cut -c1-16)"
echo '";'
