#!/bin/sh
#
# This scripts generates shellcode from the
# mmap() object code produced by gen_mmap.sh
#
# ARG1: the parasite library's name

usage () {
	echo "$0 <lib name>"
}

if [ "$#" -ne 1 ]; then
	usage
	exit 1
fi

scripts/gen_mmap.sh $1 > _shellcode.s
gcc -o _shellcode.o -c -fPIC -nostartfiles -ffreestanding -nostdlib -m32 _shellcode.s
echo "// DO NOT MODIFY: AUTOGENERATED"
echo -n "static char const mmap_shellcode[] = \""
echo -n "$(objdump -d _shellcode.o | grep -A 30 "_start>" | grep -v "_start" | cut -f 2 | tr '\n' '\ ' | sed -E 's/(\w{2})/\\x\1/g' | sed -E 's/\s+//g')"
echo "\";"
#rm -f _shellcode.s _shellcode.o
